fail gracefully on 404 during mp3 length check
Instead of using the content-length of the 404 page, fail the check with
a helpful error message.

diff --git a/.github/workflows/jekyll.yml b/.github/workflows/jekyll.yml
--- a/.github/workflows/jekyll.yml
+++ b/.github/workflows/jekyll.yml
@@ -30,7 +30,11 @@ jobs:
         for episode in _episodes/*.md; do
           length=$(grep 'length:' "$episode" | head -n1 | awk '{print $2}' | sed 's/"//g')
           file=$(grep 'file:' "$episode" | head -n1 | sed -e 's/^file: //' -e 's/"//g')
-          size=$(curl --head -s "$file" | grep content-length | awk '{print $2}' | sed 's/\r//')
+          size=$(curl --head -f -s "$file" | grep content-length | awk '{print $2}' | sed 's/\r//')
+          if [ -z $size ]; then
+            echo "couldn't get content length of \"$file\""
+            exit 1
+          fi
           if [ $size -ne $length ]; then
             echo "$(basename "$episode"): ${length}b (reported) != ${size}b (actual)"
             exit 1
